import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const migrationDir = join(ROOT, "supabase", "migrations");

function read(relativePath) {
  return readFileSync(join(ROOT, relativePath), "utf8");
}

const seed = read("supabase/seed.sql");
const b2bCatalogAlignmentMigration = read("supabase/migrations/20260814032613_align_b2b_demo_catalog.sql");
const databasePlan = read("docs/database-plan.md");
const migrationFiles = readdirSync(migrationDir).filter((file) => file.endsWith(".sql"));
const normalizedBaseline = migrationFiles.find((file) => file.includes("20260812150000_baseline_remote_schema"));
const securityMigration = migrationFiles.find((file) => file.includes("20260812150001_establish_mvp_security_contract"));

test("documentation and API schema use normalized remote table names", () => {
  for (const table of [
    "b2b_rfqs",
    "b2b_rfq_items",
    "b2c_orders",
    "b2c_order_items",
  ]) {
    assert.match(databasePlan, new RegExp("`" + table + "`"));
  }
  for (const legacyName of ["rfqs", "rfq_items", "mock_orders", "mock_order_items"]) {
    assert.doesNotMatch(databasePlan, new RegExp("`" + legacyName + "`"));
  }
});

test("seed is a non-destructive, repeatable display-data contract", () => {
  assert.match(seed, /^begin;$/m);
  assert.match(seed, /^commit;$/m);
  for (const table of [
    "companies",
    "customer_prefix_rules",
    "b2c_tags",
    "b2b_tags",
    "b2c_products",
    "b2b_products",
    "b2c_product_tags",
    "b2b_product_tags",
  ]) {
    assert.match(seed, new RegExp(`insert into public\\.${table}`));
  }
  for (const key of ["client_code", "prefix", "slug", "product_code"]) {
    assert.match(seed, new RegExp(`on conflict \\(${key}\\)`));
  }
  assert.match(seed, /insert into public\.companies \(client_code, name, is_active\)/);
  assert.doesNotMatch(seed, /insert into\s+auth\.users/i);
  assert.doesNotMatch(seed, /password/i);
  assert.match(seed, /auth_user_id 永不被/);
  assert.match(seed, /seed 覆蓋/);
});

test("the P2 migration covers exactly the three remote unindexed foreign keys", () => {
  const p2File = migrationFiles.find((file) => file.includes("add_missing_foreign_key_indexes"));
  assert.ok(p2File, "P2 index migration should be generated by Supabase CLI");
  const p2 = read(`supabase/migrations/${p2File}`);
  for (const index of [
    "b2b_rfq_items_product_id_idx",
    "b2c_order_items_mock_order_id_idx",
    "b2c_order_items_product_id_idx",
  ]) {
    assert.match(p2, new RegExp(`create index if not exists ${index}`));
  }
  assert.match(p2, /P2 performance/i);
  assert.match(p2, /20260812150000_baseline_remote_schema/);
});

const normalizedSchemaAvailable = Boolean(normalizedBaseline && securityMigration);

test(
  "normalized migrations expose the reviewed RLS and event-name contract",
  { skip: normalizedSchemaAvailable ? false : "waiting for the baseline/security migration PR to land on main" },
  () => {
    const baseline = read(`supabase/migrations/${normalizedBaseline}`);
    const security = read(`supabase/migrations/${securityMigration}`);
    const tables = [
      "companies",
      "customer_prefix_rules",
      "app_admins",
      "b2c_products",
      "b2b_products",
      "b2c_tags",
      "b2b_tags",
      "b2c_product_tags",
      "b2b_product_tags",
      "b2b_rfqs",
      "b2b_rfq_items",
      "b2c_orders",
      "b2c_order_items",
      "analytics_events",
    ];
    for (const table of tables) {
      assert.match(`${baseline}\n${security}`, new RegExp(`alter table public\\.${table} enable row level security`));
    }
    const eventConstraint = security.match(/event_name in \(([\s\S]*?)\)\s*\)/);
    assert.ok(eventConstraint, "event allowlist constraint should exist");
    const names = [...eventConstraint[1].matchAll(/'([^']+)'/g)].map(([, name]) => name);
    assert.equal(names.length, 24);
    assert.match(security, /b2b_rfqs/);
    assert.match(security, /b2c_orders/);
  },
);

test("Auth identity is outside seed ownership", () => {
  const companyInsert = seed.match(/insert into public\.companies \(([^)]+)\)/);
  assert.ok(companyInsert);
  assert.doesNotMatch(companyInsert[1], /auth_user_id/);
  assert.doesNotMatch(seed, /auth\.admin/i);
});

test("B2B demo seed matches the approved group names and category coverage", () => {
  const expectedGroups = ["食材", "加工／規格", "用途", "保存／包裝"];
  for (const group of expectedGroups) {
    assert.match(seed, new RegExp(`\\('${group}',`));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(`\\('${group}',`));
  }
  for (const legacyGroup of ["產品分類", "產品型態", "使用情境", "保存方式"]) {
    assert.doesNotMatch(seed, new RegExp(`\\('${legacyGroup}',`));
    assert.doesNotMatch(b2bCatalogAlignmentMigration, new RegExp(`\\('${legacyGroup}',`));
  }

  for (const category of ["蝦蟹類", "魚類", "貝類", "軟體類", "肉類", "調理食品"]) {
    assert.match(seed, new RegExp(`'${category}'`));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(`'${category}'`));
  }
  for (const productCode of ["B2B-SOFT-001", "B2B-MEAT-001", "B2B-PREP-001"]) {
    assert.match(seed, new RegExp(productCode));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(productCode));
  }
  for (const association of [
    "B2B-SOFT-001', 'b2b-soft-body",
    "B2B-MEAT-001', 'b2b-meat",
    "B2B-PREP-001', 'processed-food",
  ]) {
    assert.match(seed, new RegExp(association.replaceAll("'", "\\'")));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(association.replaceAll("'", "\\'")));
  }
});
