import assert from "node:assert/strict";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const migrationDir = join(ROOT, "supabase", "migrations");
const migrationFiles = readdirSync(migrationDir).filter((file) => file.endsWith(".sql"));

function read(relativePath) {
  return readFileSync(join(ROOT, relativePath), "utf8");
}

const seed = read("supabase/seed.sql");
const b2bTestFixtures = read("supabase/seed.b2b-test-fixtures.sql");
const b2bTestCleanup = read("supabase/cleanup.b2b-test-fixtures.sql");
const b2bAnalyticsFixtures = read("supabase/seed.b2b-analytics-test-fixtures.sql");
const b2bAnalyticsCleanup = read("supabase/cleanup.b2b-analytics-test-fixtures.sql");
const b2bCatalogAlignmentMigration = read("supabase/migrations/20260814032613_align_b2b_demo_catalog.sql");
const b2bSpecOptionsMigrationFile = migrationFiles.find((file) => file.includes("b2b_product_spec_options"));
const b2bSpecOptionsMigration = b2bSpecOptionsMigrationFile
  ? read(`supabase/migrations/${b2bSpecOptionsMigrationFile}`)
  : "";
const adminCatalogMigrationFile = migrationFiles
  .filter((file) => file.includes("admin_catalog_media_and_management"))
  .sort()
  .at(-1);
const adminCatalogMigration = adminCatalogMigrationFile
  ? read(`supabase/migrations/${adminCatalogMigrationFile}`)
  : "";
const adminRolesStatusMigrationFile = migrationFiles.find((file) => file.includes("add_admin_roles_and_b2b_status"));
const adminRolesStatusMigration = adminRolesStatusMigrationFile
  ? read(`supabase/migrations/${adminRolesStatusMigrationFile}`)
  : "";
const adminBulkStatusFixFile = migrationFiles.find((file) => file.includes("fix_admin_bulk_status_ambiguity"));
const adminBulkStatusFix = adminBulkStatusFixFile
  ? read(`supabase/migrations/${adminBulkStatusFixFile}`)
  : "";
const b2bFinderChannelMigrationFile = migrationFiles.find((file) =>
  file.includes("b2b_product_finder_channel_tags"),
);
const b2bFinderChannelMigration = b2bFinderChannelMigrationFile
  ? read(`supabase/migrations/${b2bFinderChannelMigrationFile}`)
  : "";
const databasePlan = read("docs/database-plan.md");
const normalizedBaseline = migrationFiles.find((file) => file.includes("20260812150000_baseline_remote_schema"));
const securityMigration = migrationFiles.find((file) => file.includes("20260812150001_establish_mvp_security_contract"));

test("documentation and API schema use normalized remote table names", () => {
  for (const table of [
    "b2b_rfqs",
    "b2b_rfq_items",
    "b2c_orders",
    "b2c_order_items",
  ]) {
    assert.match(databasePlan, new RegExp("`" + table + "`"));
  }
  for (const legacyName of ["rfqs", "rfq_items", "mock_orders", "mock_order_items"]) {
    assert.doesNotMatch(databasePlan, new RegExp("`" + legacyName + "`"));
  }
});

test("seed is a non-destructive, repeatable display-data contract", () => {
  assert.match(seed, /^begin;$/m);
  assert.match(seed, /^commit;$/m);
  for (const table of [
    "companies",
    "customer_prefix_rules",
    "b2c_tags",
    "b2b_tags",
    "b2c_products",
    "b2b_products",
    "b2b_product_spec_options",
    "b2c_product_tags",
    "b2b_product_tags",
  ]) {
    assert.match(seed, new RegExp(`insert into public\\.${table}`));
  }
  for (const key of ["client_code", "prefix", "slug", "product_code"]) {
    assert.match(seed, new RegExp(`on conflict \\(${key}\\)`));
  }
  assert.match(seed, /insert into public\.companies \(client_code, name, is_active\)/);
  assert.doesNotMatch(seed, /insert into\s+auth\.users/i);
  assert.doesNotMatch(seed, /password/i);
  assert.match(seed, /auth_user_id 永不被/);
  assert.match(seed, /seed 覆蓋/);
});

test("the P2 migration covers exactly the three remote unindexed foreign keys", () => {
  const p2File = migrationFiles.find((file) => file.includes("add_missing_foreign_key_indexes"));
  assert.ok(p2File, "P2 index migration should be generated by Supabase CLI");
  const p2 = read(`supabase/migrations/${p2File}`);
  for (const index of [
    "b2b_rfq_items_product_id_idx",
    "b2c_order_items_mock_order_id_idx",
    "b2c_order_items_product_id_idx",
  ]) {
    assert.match(p2, new RegExp(`create index if not exists ${index}`));
  }
  assert.match(p2, /P2 performance/i);
  assert.match(p2, /20260812150000_baseline_remote_schema/);
});

const normalizedSchemaAvailable = Boolean(normalizedBaseline && securityMigration);

test(
  "normalized migrations expose the reviewed RLS and event-name contract",
  { skip: normalizedSchemaAvailable ? false : "waiting for the baseline/security migration PR to land on main" },
  () => {
    const baseline = read(`supabase/migrations/${normalizedBaseline}`);
    const security = read(`supabase/migrations/${securityMigration}`);
    const tables = [
      "companies",
      "customer_prefix_rules",
      "app_admins",
      "b2c_products",
      "b2b_products",
      "b2c_tags",
      "b2b_tags",
      "b2c_product_tags",
      "b2b_product_tags",
      "b2b_rfqs",
      "b2b_rfq_items",
      "b2c_orders",
      "b2c_order_items",
      "analytics_events",
    ];
    for (const table of tables) {
      assert.match(`${baseline}\n${security}`, new RegExp(`alter table public\\.${table} enable row level security`));
    }
    const eventConstraint = security.match(/event_name in \(([\s\S]*?)\)\s*\)/);
    assert.ok(eventConstraint, "event allowlist constraint should exist");
    const names = [...eventConstraint[1].matchAll(/'([^']+)'/g)].map(([, name]) => name);
    assert.equal(names.length, 24);
    assert.match(security, /b2b_rfqs/);
    assert.match(security, /b2c_orders/);
  },
);

test("Auth identity is outside seed ownership", () => {
  const companyInsert = seed.match(/insert into public\.companies \(([^)]+)\)/);
  assert.ok(companyInsert);
  assert.doesNotMatch(companyInsert[1], /auth_user_id/);
  assert.doesNotMatch(seed, /auth\.admin/i);
});

test("B2B multi-spec migration and seed preserve option identity and ordering", () => {
  assert.ok(b2bSpecOptionsMigrationFile, "B2B spec option migration should exist");
  for (const field of [
    "option_code",
    "specification_text",
    "packaging_text",
    "is_active",
    "display_order",
  ]) {
    assert.match(b2bSpecOptionsMigration, new RegExp(field));
  }
  assert.match(b2bSpecOptionsMigration, /enable row level security/);
  assert.match(b2bSpecOptionsMigration, /grant select on table public\.b2b_product_spec_options to authenticated/);
  assert.match(b2bSpecOptionsMigration, /rfq_items_specification_option_product_fkey/);
  assert.match(b2bSpecOptionsMigration, /specification_text_snapshot/);
  assert.match(b2bSpecOptionsMigration, /other_specification/);
  assert.match(b2bSpecOptionsMigration, /other_packaging/);
  assert.match(seed, /insert into public\.b2b_product_spec_options/);
  assert.match(seed, /on conflict \(option_code\) do update/);
  for (const optionCode of [
    "B2B-FISH-001-200G",
    "B2B-FISH-001-300G",
    "B2B-FISH-001-500G",
  ]) {
    assert.match(seed, new RegExp(optionCode));
  }
  assert.match(seed, /other.*customer|客戶輸入/);
});

test("admin catalog migration protects product images and batch imports", () => {
  assert.ok(adminCatalogMigrationFile, "admin catalog migration should exist");
  for (const table of ["b2c_product_images", "b2b_product_images"]) {
    assert.match(adminCatalogMigration, new RegExp(`create table(?: if not exists)? public\\.${table}`));
    assert.match(adminCatalogMigration, new RegExp(`${table}_one_cover_idx`));
    assert.match(adminCatalogMigration, new RegExp(`${table}.*enable row level security`, "s"));
  }
  assert.match(adminCatalogMigration, /image_role.*cover.*detail/s);
  assert.match(adminCatalogMigration, /storage_path text not null unique/);
  assert.match(adminCatalogMigration, /file_size_limit,\s*allowed_mime_types/);
  assert.match(adminCatalogMigration, /'b2c-media'.*true/s);
  assert.match(adminCatalogMigration, /'b2b-media'.*false/s);
  assert.match(adminCatalogMigration, /image\/jpeg.*image\/png.*image\/webp/s);
  assert.match(adminCatalogMigration, /admin_insert_b2b_products_batch/);
  assert.match(adminCatalogMigration, /jsonb_to_recordset/);
  assert.match(adminCatalogMigration, /grant execute on function public\.admin_insert_b2b_products_batch\(jsonb\)\s*to service_role/s);
});

test("B2B status and admin role migration preserve the acceptance matrix", () => {
  assert.ok(adminRolesStatusMigrationFile, "admin role/status migration should exist");
  assert.match(adminRolesStatusMigration, /role text not null default 'admin'/);
  assert.match(adminRolesStatusMigration, /'admin', 'business_staff'/);
  assert.match(adminRolesStatusMigration, /status text/);
  assert.match(adminRolesStatusMigration, /'draft', 'review', 'published', 'offline'/);
  assert.match(adminRolesStatusMigration, /status = 'published'/);
  assert.match(adminRolesStatusMigration, /admin_bulk_update_b2b_product_status/);
  assert.match(adminRolesStatusMigration, /product\.status = 'draft' and next_status = 'review'/);
  assert.match(adminRolesStatusMigration, /product\.status = 'review' and next_status in \('draft', 'published'\)/);
  assert.match(adminRolesStatusMigration, /product\.status = 'published' and next_status = 'offline'/);
  assert.match(adminRolesStatusMigration, /product\.status = 'offline' and next_status = 'published'/);
  assert.ok(adminBulkStatusFixFile, "bulk status ambiguity fix should be generated by Supabase CLI");
  assert.match(adminBulkStatusFix, /from public\.b2b_products as product\s+where product\.id = any\(product_ids\)/);
});

test("B2B authorization fixtures are isolated, repeatable and safely removable", () => {
  assert.match(b2bTestFixtures, /^begin;$/m);
  assert.match(b2bTestFixtures, /^commit;$/m);
  assert.match(b2bTestFixtures, /B2B-TEST-INACTIVE-001/);
  assert.match(b2bTestFixtures, /E853699/);
  assert.match(b2bTestFixtures, /W483038/);
  assert.match(b2bTestFixtures, /status\s*\)\s*values\s*\([\s\S]*'offline'/);
  assert.match(b2bTestFixtures, /on conflict \(client_code\) do update/);
  assert.match(b2bTestFixtures, /on conflict \(product_code\) do update/);
  assert.doesNotMatch(b2bTestFixtures, /auth\.users|auth\.admin|password/i);
  assert.match(b2bTestCleanup, /B2B-TEST-INACTIVE-001/);
  assert.match(b2bTestCleanup, /E853699/);
  assert.match(b2bTestCleanup, /W483038/);
  assert.match(b2bTestCleanup, /auth_user_id is null/);
  assert.match(b2bTestCleanup, /not exists/);
});

test("B2B Analytics fixtures are isolated, complete and safely removable", () => {
  assert.match(b2bAnalyticsFixtures, /^begin;$/m);
  assert.match(b2bAnalyticsFixtures, /^commit;$/m);
  assert.match(b2bAnalyticsFixtures, /W483038/);
  assert.match(b2bAnalyticsFixtures, /auth_user_id is not null/);
  assert.match(b2bAnalyticsFixtures, /fixture-b2b-analytics-/);
  assert.match(b2bAnalyticsFixtures, /fixture:b2b-analytics:rfq-1/);
  for (const eventName of [
    "b2b_login_success",
    "b2b_catalog_view",
    "b2b_product_view",
    "b2b_search_filter",
    "b2b_product_finder_start",
    "b2b_product_finder_answer",
    "b2b_product_finder_complete",
    "b2b_product_finder_result_click",
    "b2b_rfq_add",
    "b2b_rfq_submit",
  ]) {
    assert.match(b2bAnalyticsFixtures, new RegExp(eventName));
  }
  assert.doesNotMatch(b2bAnalyticsFixtures, /auth\.users|auth\.admin|password/i);
  assert.match(b2bAnalyticsCleanup, /fixture-b2b-analytics-/);
  assert.match(b2bAnalyticsCleanup, /fixture:b2b-analytics:rfq-1/);
});

test("B2B demo seed matches the approved group names and category coverage", () => {
  const expectedGroups = ["食材", "加工／規格", "用途", "保存／包裝"];
  for (const group of expectedGroups) {
    assert.match(seed, new RegExp(`\\('${group}',`));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(`\\('${group}',`));
  }
  for (const legacyGroup of ["產品分類", "產品型態", "使用情境", "保存方式"]) {
    assert.doesNotMatch(seed, new RegExp(`\\('${legacyGroup}',`));
    assert.doesNotMatch(b2bCatalogAlignmentMigration, new RegExp(`\\('${legacyGroup}',`));
  }

  for (const category of ["蝦蟹類", "魚類", "貝類", "軟體類", "肉類", "調理食品"]) {
    assert.match(seed, new RegExp(`'${category}'`));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(`'${category}'`));
  }
  for (const productCode of ["B2B-SOFT-001", "B2B-MEAT-001", "B2B-PREP-001"]) {
    assert.match(seed, new RegExp(productCode));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(productCode));
  }
  for (const association of [
    "B2B-SOFT-001', 'b2b-soft-body",
    "B2B-MEAT-001', 'b2b-meat",
    "B2B-PREP-001', 'processed-food",
  ]) {
    assert.match(seed, new RegExp(association.replaceAll("'", "\\'")));
    assert.match(b2bCatalogAlignmentMigration, new RegExp(association.replaceAll("'", "\\'")));
  }
});

test("B2B product finder stores the approved channel leaves as product tags", () => {
  assert.ok(b2bFinderChannelMigrationFile, "B2B finder channel migration should exist");
  const leafSlugs = [
    "wholesale_small",
    "wholesale_mid_large",
    "ecommerce_group_buy",
    "ecommerce_live",
    "ecommerce_marketplace",
    "mass_retail",
    "traditional_market",
    "seafood_specialty_store",
    "foodservice_general",
    "foodservice_chain",
    "foodservice_banquet_catering",
    "foodservice_hotel",
  ];

  assert.match(b2bFinderChannelMigration, /insert into public\.b2b_tags/);
  assert.match(b2bFinderChannelMigration, /group_name, slug, name, is_active/);
  assert.match(b2bFinderChannelMigration, /on conflict \(slug\) do update/);
  assert.match(b2bFinderChannelMigration, /insert into public\.b2b_product_tags/);
  assert.match(b2bFinderChannelMigration, /on conflict \(product_id, tag_id\) do nothing/);
  for (const slug of leafSlugs) {
    assert.match(b2bFinderChannelMigration, new RegExp(`'${slug}'`));
    assert.match(seed, new RegExp(`'${slug}'`));
  }
  for (const mapping of [
    "B2B-SHRIMP-001', 'wholesale_small",
    "B2B-PREP-001', 'ecommerce_group_buy",
    "B2B-SHELL-001', 'mass_retail",
    "B2B-FISH-003', 'foodservice_chain",
  ]) {
    const pattern = new RegExp(mapping.replaceAll("'", "\\'"));
    assert.match(b2bFinderChannelMigration, pattern);
    assert.match(seed, pattern);
  }
});
