"use client";

import Image from "next/image";
import { useMemo, useState } from "react";

type PreviewProduct = { code: string; name: string; category: string; series: string; specification: string; packaging: string; origin: string; image: string };
const products: PreviewProduct[] = [
  { code: "B2B-FISH-001", name: "智利鮭魚切片", category: "魚類", series: "鮭魚系列", specification: "200g／片", packaging: "20片／箱", origin: "智利", image: "/products/b2b/B2B-FISH-001/main.jpg" },
  { code: "B2B-FISH-002", name: "午仔魚整尾", category: "魚類", series: "整尾魚", specification: "450–550g／尾", packaging: "10尾／箱", origin: "台灣", image: "/products/b2b/B2B-FISH-002/main.jpg" },
  { code: "B2B-SHRIMP-001", name: "白蝦原料", category: "蝦蟹類", series: "白蝦系列", specification: "31／40尾／磅", packaging: "2kg／包", origin: "厄瓜多", image: "/products/b2b/B2B-SHRIMP-001/main.jpg" },
  { code: "B2B-SHELL-001", name: "熟凍扇貝", category: "貝類", series: "干貝系列", specification: "20／30規格", packaging: "5kg／箱", origin: "日本", image: "/products/b2b/B2B-SHELL-001/main.jpg" },
  { code: "B2B-SOFT-001", name: "透抽圈", category: "軟體類", series: "透抽系列", specification: "切圈規格", packaging: "10kg／箱", origin: "印尼", image: "/products/b2b/B2B-SOFT-001/main.jpg" },
  { code: "B2B-MEAT-001", name: "去骨雞腿肉切塊", category: "肉類", series: "雞肉系列", specification: "切塊規格", packaging: "10kg／箱", origin: "台灣", image: "/products/b2b/B2B-MEAT-001/main.jpg" },
];
const categories = ["全部", "魚類", "蝦蟹類", "貝類", "軟體類", "肉類"];

export default function EditorialCatalogPreview() {
  const [category, setCategory] = useState("全部"); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<PreviewProduct | null>(null); const [inquiryOpen, setInquiryOpen] = useState(false); const [inquiry, setInquiry] = useState<PreviewProduct[]>([]);
  const visible = useMemo(() => products.filter((product) => { const term = query.trim().toLocaleLowerCase("zh-Hant"); return (category === "全部" || product.category === category) && (!term || [product.code, product.name, product.series, product.specification].join(" ").toLocaleLowerCase("zh-Hant").includes(term)); }), [category, query]);
  function add(product: PreviewProduct) { setInquiry((current) => current.some((item) => item.code === product.code) ? current : [...current, product]); setInquiryOpen(true); }
  return <main className="min-h-screen bg-[#f7f4ee] text-[#2b2b2b]" style={{ fontFamily: '"Noto Sans TC", "Microsoft JhengHei", sans-serif' }}>
    <header className="border-b border-[#ded8cf] bg-[#fbfaf7]"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-5 lg:px-12"><div className="flex items-center gap-4"><div className="grid size-12 place-items-center rounded-full bg-[#2e613f] text-xl font-bold text-[#f7f4ee]">元</div><div><p className="text-[11px] font-bold tracking-[.28em] text-[#2e613f]">YUANJIA BUSINESS</p><h1 className="mt-1 font-serif text-xl tracking-[.08em]">企業型錄</h1></div></div><button className="border-b border-[#2e613f] px-1 py-2 text-sm tracking-[.08em] text-[#2e613f]" onClick={() => setInquiryOpen(true)} type="button">詢價單 {inquiry.length ? `(${inquiry.length})` : ""}</button></div></header>
    <section className="relative overflow-hidden border-b border-[#cfc8bd]"><Image alt="全球冷凍水產食材供應服務" className="h-[270px] w-full object-cover brightness-[.68] sm:h-[350px]" height={600} priority src="/brand/yuanjia-banner.jpg" width={1900} /><div className="absolute inset-0 flex items-end bg-gradient-to-t from-[#182b27]/80 via-transparent to-transparent"><div className="mx-auto w-full max-w-[1440px] px-6 pb-10 lg:px-12"><p className="text-xs font-bold tracking-[.3em] text-[#e9d9b8]">01 / BUSINESS CATALOG</p><h2 className="mt-3 max-w-xl font-serif text-4xl leading-tight text-[#fffaf0] sm:text-5xl">全球冷凍水產<br />企業採購服務</h2><p className="mt-4 text-sm tracking-[.08em] text-[#f0e8dc]">規格、包裝、產地與保存資訊，集中交由業務確認。</p></div></div></section>
    <div className="mx-auto max-w-[1440px] px-6 py-12 lg:px-12"><div className="mb-10 flex flex-col gap-6 border-b border-[#d8d0c5] pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold tracking-[.25em] text-[#2e613f]">PRODUCT INDEX</p><h2 className="mt-3 font-serif text-3xl tracking-[.05em]">找尋適合您的食材</h2></div><p className="max-w-xs text-sm leading-7 text-[#6c6a63]">以產品大類快速瀏覽，再用品名、品號或規格縮小範圍。</p></div><div className="mb-10 grid gap-5 lg:grid-cols-[240px_1fr]"><aside className="border-y border-[#d8d0c5] py-5 lg:border-y-0 lg:border-r lg:pr-7"><label className="text-xs font-bold tracking-[.18em] text-[#6c6a63]">SEARCH PRODUCTS<input className="mt-3 w-full border-b border-[#a9a196] bg-transparent px-0 py-3 text-sm outline-none placeholder:text-[#9b948a] focus:border-[#2e613f]" onChange={(event) => setQuery(event.target.value)} placeholder="品名、商品編號、規格" value={query} /></label><p className="mt-8 text-xs font-bold tracking-[.18em] text-[#6c6a63]">CATEGORY</p><div className="mt-3 space-y-1">{categories.map((item) => <button className={`block w-full border-b border-[#e6e0d7] py-3 text-left text-sm transition ${category === item ? "font-bold text-[#2e613f]" : "text-[#6c6a63] hover:pl-2 hover:text-[#2e613f]"}`} key={item} onClick={() => setCategory(item)} type="button">{item}<span className="float-right">{category === item ? "—" : "＋"}</span></button>)}</div></aside><section><div className="mb-5 flex items-center justify-between"><p className="text-xs tracking-[.15em] text-[#6c6a63]">{category === "全部" ? "ALL PRODUCTS" : category} / {visible.length} ITEMS</p><p className="hidden text-xs text-[#8a8379] sm:block">價格與供應狀況由業務確認</p></div><div className="grid gap-x-5 gap-y-10 sm:grid-cols-2 xl:grid-cols-3">{visible.map((product, index) => <article className="group" key={product.code}><button className="block w-full text-left" onClick={() => setSelected(product)} type="button"><div className="relative aspect-[4/3] overflow-hidden bg-[#e8e4dc]"><Image alt={product.name} className="object-cover transition duration-500 group-hover:scale-[1.04]" fill sizes="(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 33vw" src={product.image} /></div><div className="flex items-start justify-between gap-3 border-b border-[#d8d0c5] py-4"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#2e613f]">{String(index + 1).padStart(2, "0")} / {product.code}</p><h3 className="mt-2 font-serif text-xl">{product.name}</h3><p className="mt-1 text-sm text-[#6c6a63]">{product.series}・{product.origin}</p></div><span className="mt-1 text-xs text-[#6c6a63]">查看 →</span></div></button><button className="mt-3 text-xs font-bold tracking-[.08em] text-[#2e613f] underline underline-offset-4 hover:text-[#193d28]" onClick={() => add(product)} type="button">加入詢價單</button></article>)}</div></section></div></div>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-[#1e2b25]/45 p-4" onClick={() => setSelected(null)}><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto bg-[#fbfaf7] p-5 sm:p-8" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between border-b border-[#d8d0c5] pb-5"><div><p className="text-xs font-bold tracking-[.2em] text-[#2e613f]">PRODUCT DETAIL</p><h2 className="mt-2 font-serif text-3xl">{selected.name}</h2><p className="mt-2 text-sm text-[#6c6a63]">{selected.code}・元家・{selected.category}</p></div><button aria-label="關閉商品細項" className="text-2xl text-[#6c6a63]" onClick={() => setSelected(null)} type="button">×</button></div><div className="grid gap-7 py-7 sm:grid-cols-[1fr_1fr]"><div className="relative aspect-square overflow-hidden bg-[#e8e4dc]"><Image alt={selected.name} className="object-cover" fill sizes="(max-width: 640px) 100vw, 50vw" src={selected.image} /></div><div><dl className="divide-y divide-[#ded8cf] border-y border-[#ded8cf] text-sm"><div className="grid grid-cols-[5rem_1fr] py-4"><dt className="font-bold">規格</dt><dd>{selected.specification}</dd></div><div className="grid grid-cols-[5rem_1fr] py-4"><dt className="font-bold">包裝</dt><dd>{selected.packaging}</dd></div><div className="grid grid-cols-[5rem_1fr] py-4"><dt className="font-bold">產地</dt><dd>{selected.origin}</dd></div></dl><p className="mt-6 text-sm leading-7 text-[#6c6a63]">實際規格、供應與交期由所屬業務確認；本頁不顯示價格或即時庫存。</p><button className="mt-7 w-full bg-[#2e613f] px-5 py-4 text-sm font-bold tracking-[.08em] text-[#fffaf0] transition hover:bg-[#193d28]" onClick={() => add(selected)} type="button">選擇規格・加入詢價單</button></div></div></section></div>}
    {inquiryOpen && <aside className="fixed inset-y-0 right-0 z-[60] w-full max-w-sm border-l border-[#d8d0c5] bg-[#fbfaf7] p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-[#d8d0c5] pb-5"><div><p className="text-xs font-bold tracking-[.2em] text-[#2e613f]">INQUIRY LIST</p><h2 className="mt-2 font-serif text-2xl">詢價單</h2></div><button aria-label="關閉詢價單" className="text-2xl text-[#6c6a63]" onClick={() => setInquiryOpen(false)} type="button">×</button></div>{inquiry.length ? <ul className="divide-y divide-[#ded8cf]">{inquiry.map((item) => <li className="py-5" key={item.code}><p className="font-serif text-lg">{item.name}</p><p className="mt-1 text-xs text-[#6c6a63]">{item.specification}・{item.packaging}</p><button className="mt-3 text-xs text-[#2e613f] underline" onClick={() => setInquiry((current) => current.filter((entry) => entry.code !== item.code))} type="button">移除</button></li>)}</ul> : <p className="py-12 text-center text-sm text-[#6c6a63]">尚未選擇商品</p>}<button className="mt-6 w-full bg-[#2e613f] px-4 py-4 text-sm font-bold text-[#fffaf0]" disabled={!inquiry.length} type="button">確認詢價內容</button></aside>}
  </main>;
}
