"use client";

import { useState } from "react";

type Product = { code: string; name: string; group: string; series: string; specification: string; packaging: string; origin: string };

const tree = [
  { name: "魚類", children: ["全部魚類", "鮭魚系列", "石斑系列", "整尾魚", "魚類加工", "魚類調味"] },
  { name: "蝦蟹類", children: ["全部蝦蟹", "蝦仁", "白蝦", "草蝦", "蟹類"] },
  { name: "貝類", children: ["全部貝類", "干貝", "牡蠣", "蛤蜊", "鮑魚"] },
  { name: "軟體類", children: ["全部軟體", "花枝", "魷魚", "章魚"] },
  { name: "肉類", children: ["全部肉類", "雞肉", "豬肉", "牛肉"] },
  { name: "調理食品類", children: ["全部調理", "湯品", "調味", "裹粉酥炸"] },
] as const;

const allProducts: Product[] = [
  { code: "B2B-FISH-001", name: "智利鮭魚切片", group: "魚類", series: "鮭魚系列", specification: "200g／片", packaging: "20片／箱", origin: "智利" },
  { code: "B2B-FISH-002", name: "午仔魚整尾", group: "魚類", series: "整尾魚", specification: "450–550g／尾", packaging: "10尾／箱", origin: "台灣" },
  { code: "B2B-FISH-003", name: "鯛魚菲力", group: "魚類", series: "魚類加工", specification: "120–150g／片", packaging: "10kg／箱", origin: "台灣" },
  { code: "B2B-SHELL-001", name: "熟凍扇貝", group: "貝類", series: "干貝", specification: "20／30規格", packaging: "5kg／箱", origin: "日本" },
];

export default function CatalogBannerDrawerPreview() {
  const [group, setGroup] = useState("魚類");
  const [series, setSeries] = useState("全部魚類");
  const [query, setQuery] = useState("");
  const [items, setItems] = useState<Product[]>([]);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [detailProduct, setDetailProduct] = useState<Product | null>(null);
  const currentTree = tree.find((item) => item.name === group) ?? tree[0];
  const visible = allProducts.filter((product) => {
    const term = query.trim().toLocaleLowerCase("zh-Hant");
    return product.group === group && (series.startsWith("全部") || product.series === series) && (!term || [product.code, product.name, product.specification, product.packaging].join(" ").toLocaleLowerCase("zh-Hant").includes(term));
  });
  const chooseGroup = (next: string) => { const selection = tree.find((item) => item.name === next) ?? tree[0]; setGroup(next); setSeries(selection.children[0]); };
  const addItem = (product: Product) => { setItems((old) => old.some((item) => item.code === product.code) ? old : [...old, product]); setDrawerOpen(true); };

  return <main className="min-h-screen bg-[#F7F6F2] text-[#17242A]" style={{ fontFamily: '"Noto Sans TC", "Microsoft JhengHei", system-ui, sans-serif' }}>
    <header className="sticky top-0 z-40 border-b border-[#D9E1E5] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1400px] items-center justify-between gap-3 px-4 py-3 sm:px-5 lg:px-8"><div className="min-w-0"><p className="hidden text-xs font-bold tracking-[.16em] text-[#005DAA] sm:block">YUANJIA BUSINESS</p><h1 className="truncate text-base font-bold sm:mt-1 sm:text-xl">元家 B2B・企業型錄</h1></div><button className="shrink-0 rounded-lg border border-[#8FB8CD] bg-[#F4FAFD] px-3 py-2 text-sm font-bold text-[#005DAA] sm:px-4" onClick={() => setDrawerOpen(true)} type="button">詢價單{items.length ? `（${items.length}）` : ""}</button></div></header>
    <section className="relative overflow-hidden bg-[#15242C]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_46%,rgba(45,126,140,.5),transparent_20%),radial-gradient(circle_at_86%_45%,rgba(227,90,39,.7),transparent_13%),linear-gradient(90deg,rgba(9,20,26,.98),rgba(17,38,47,.85),rgba(18,55,63,.4))]" /><div className="relative mx-auto max-w-[1400px] px-5 py-10 lg:px-8 lg:py-14"><p className="text-xs font-bold tracking-[.18em] text-[#BFDCF0]">YUANJIA BUSINESS CATALOG</p><h2 className="mt-3 text-3xl font-bold leading-tight text-white sm:text-4xl">全球冷凍<br />水產食材供應服務</h2><p className="mt-4 max-w-lg text-sm leading-6 text-[#D6E7EE]">以元家既有產品分類為入口，快速確認品項、規格與包裝，集中交由業務報價。</p></div></section>
    <div className="mx-auto max-w-[1400px] px-5 py-7 lg:px-8"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.14em] text-[#005DAA]">BUSINESS CATALOG</p><h2 className="mt-1 text-2xl font-bold">企業產品型錄</h2></div><p className="text-sm font-semibold text-[#00457F]">共 2,000+ 項商品</p></div><div className="grid gap-5 lg:grid-cols-[15rem_minmax(0,1fr)]">
      <aside className="h-fit rounded-2xl border border-[#D9E1E5] bg-white p-5 shadow-[0_8px_20px_rgba(23,36,42,.04)] lg:sticky lg:top-5"><p className="text-xs font-bold tracking-[.14em] text-[#005DAA]">CATALOG FILTER</p><h3 className="mt-2 text-lg font-bold">篩選商品</h3><label className="mt-5 block text-sm font-semibold">直接搜尋<input className="mt-2 min-h-10 w-full rounded-lg border border-[#CBD8DE] px-3 text-sm font-normal outline-none focus:border-[#005DAA] focus:ring-4 focus:ring-[#EAF5FB]" onChange={(event) => setQuery(event.target.value)} placeholder="品名、品號、規格" value={query} /></label><div className="mt-5 border-t border-[#E2E8EB] pt-5"><p className="text-sm font-bold">產品大類</p>{tree.map((item) => <button className={`mt-1 flex min-h-9 w-full items-center justify-between rounded-md px-2 text-left text-sm font-semibold ${item.name === group ? "bg-[#005DAA] text-white" : "text-[#40525A] hover:bg-[#EAF5FB]"}`} key={item.name} onClick={() => chooseGroup(item.name)} type="button">{item.name}<span>›</span></button>)}</div><div className="mt-5 border-t border-[#E2E8EB] pt-5"><p className="text-sm font-bold">{group}・系列／魚種</p>{currentTree.children.map((child) => <button className={`mt-1 min-h-8 w-full rounded-md px-2 text-left text-sm ${child === series ? "bg-[#EAF5FB] font-bold text-[#005DAA]" : "text-[#536168] hover:bg-[#F4FAFD]"}`} key={child} onClick={() => setSeries(child)} type="button">{child}</button>)}</div><details className="mt-5 border-t border-[#E2E8EB] pt-4"><summary className="cursor-pointer text-sm font-bold">更多採購條件</summary><div className="mt-3 space-y-2 text-sm text-[#536168]"><label className="block"><input className="mr-2" type="checkbox" />切片／菲力</label><label className="block"><input className="mr-2" type="checkbox" />冷凍保存</label><label className="block"><input className="mr-2" type="checkbox" />箱裝</label></div></details></aside>
      <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#D6E8F2] bg-white px-4 py-3"><div><p className="text-xs font-bold tracking-[.12em] text-[#005DAA]">目前瀏覽</p><h3 className="mt-1 font-bold">{group} ＞ {series}</h3></div><p className="text-sm text-[#536168]">找到 {visible.length} 項展示商品</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visible.map((product) => <article className="overflow-hidden rounded-2xl border border-[#D9E1E5] bg-white shadow-[0_6px_18px_rgba(23,36,42,.04)]" key={product.code}><div className="relative grid aspect-[16/8] place-items-center overflow-hidden bg-[#EAF5FB]"><div className="absolute -right-6 -top-8 size-32 rounded-full border-[18px] border-[#CFE3F0]" /><span className="relative rounded-full border border-[#9DC6DD] bg-white px-3 py-2 text-sm font-bold text-[#005DAA]">{product.group}</span><p className="absolute bottom-3 left-3 text-[10px] font-bold tracking-[.14em] text-[#536168]">PRODUCT REFERENCE</p></div><div className="p-4"><p className="text-xs font-bold tracking-[.08em] text-[#005DAA]">{product.code}</p><h4 className="mt-2 text-lg font-bold">{product.name}</h4><p className="mt-1 text-sm text-[#536168]">元家・{product.series}</p><dl className="mt-4 grid gap-2 border-t border-[#E2E8EB] pt-3 text-sm"><div className="grid grid-cols-[3rem_1fr]"><dt className="font-semibold text-[#536168]">規格</dt><dd>{product.specification}</dd></div><div className="grid grid-cols-[3rem_1fr]"><dt className="font-semibold text-[#536168]">包裝</dt><dd>{product.packaging}</dd></div><div className="grid grid-cols-[3rem_1fr]"><dt className="font-semibold text-[#536168]">產地</dt><dd>{product.origin}</dd></div></dl><div className="mt-4 grid grid-cols-2 gap-2"><button className="min-h-10 rounded-lg border border-[#8FB8CD] text-sm font-bold text-[#005DAA] hover:bg-[#EAF5FB]" onClick={() => setDetailProduct(product)} type="button">查看細項</button><button className="min-h-10 rounded-lg bg-[#005DAA] text-sm font-bold text-white hover:bg-[#00457F]" onClick={() => addItem(product)} type="button">加入詢價單</button></div></div></article>)}{!visible.length && <div className="rounded-xl border border-dashed border-[#B9CCD5] bg-white p-10 text-center text-sm text-[#536168]">此條件暫無展示商品，請改選系列或清除搜尋文字。</div>}</div></section>
    </div></div>
    {detailProduct && <div className="fixed inset-0 z-50 grid place-items-end bg-[#17242A]/40 p-4 sm:place-items-center" role="presentation"><section aria-modal="true" className="w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl" role="dialog"><div className="flex items-start justify-between border-b border-[#D9E1E5] p-5"><div><p className="text-xs font-bold tracking-[.14em] text-[#005DAA]">PRODUCT DETAIL</p><h2 className="mt-2 text-2xl font-bold">{detailProduct.name}</h2><p className="mt-1 text-sm text-[#536168]">{detailProduct.code}・元家・{detailProduct.series}</p></div><button aria-label="關閉商品細項" className="grid size-10 place-items-center rounded-full text-xl text-[#536168] hover:bg-[#F1F5F7]" onClick={() => setDetailProduct(null)} type="button">×</button></div><div className="grid gap-6 p-5 sm:grid-cols-[1fr_1.15fr]"><div className="relative grid min-h-52 place-items-center overflow-hidden rounded-xl bg-[#EAF5FB]"><div className="absolute -right-7 -top-7 size-36 rounded-full border-[20px] border-[#CFE3F0]" /><span className="relative rounded-full border border-[#9DC6DD] bg-white px-4 py-3 font-bold text-[#005DAA]">{detailProduct.group}</span></div><div><h3 className="font-bold">產品細項</h3><dl className="mt-3 grid gap-3 text-sm"><div className="grid grid-cols-[4.5rem_1fr]"><dt className="font-semibold text-[#536168]">規格</dt><dd>{detailProduct.specification}</dd></div><div className="grid grid-cols-[4.5rem_1fr]"><dt className="font-semibold text-[#536168]">箱容／包裝</dt><dd>{detailProduct.packaging}</dd></div><div className="grid grid-cols-[4.5rem_1fr]"><dt className="font-semibold text-[#536168]">產地</dt><dd>{detailProduct.origin}</dd></div><div className="grid grid-cols-[4.5rem_1fr]"><dt className="font-semibold text-[#536168]">保存方式</dt><dd>冷凍 -18°C 以下</dd></div><div className="grid grid-cols-[4.5rem_1fr]"><dt className="font-semibold text-[#536168]">適用通路</dt><dd>餐飲、團膳、零售採購</dd></div></dl><p className="mt-5 border-t border-[#E2E8EB] pt-4 text-sm leading-6 text-[#536168]">完整品項頁可放產品特色、料理方式、認證與相關文件；實際規格、供應與價格由所屬業務確認。</p><button className="mt-5 min-h-11 w-full rounded-lg bg-[#005DAA] text-sm font-bold text-white" onClick={() => { addItem(detailProduct); setDetailProduct(null); }} type="button">加入詢價單</button></div></div></section></div>}
    {drawerOpen && <div className="fixed inset-0 z-50 flex justify-end bg-[#17242A]/30" role="presentation"><aside aria-label="詢價單" className="h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-[#D9E1E5] pb-5"><div><p className="text-xs font-bold tracking-[.14em] text-[#005DAA]">INQUIRY LIST</p><h2 className="mt-2 text-2xl font-bold">詢價單</h2><p className="mt-1 text-sm text-[#536168]">已選 {items.length} 項商品</p></div><button aria-label="關閉詢價單，繼續瀏覽商品" className="grid size-10 place-items-center rounded-full text-xl text-[#536168] hover:bg-[#F1F5F7]" onClick={() => setDrawerOpen(false)} type="button">×</button></div>{items.length ? <ul className="divide-y divide-[#E2E8EB]">{items.map((item) => <li className="py-4" key={item.code}><div className="flex justify-between gap-4"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-[#536168]">{item.specification}・{item.packaging}</p></div><button className="text-sm font-bold text-[#005DAA]" onClick={() => setItems((old) => old.filter((entry) => entry.code !== item.code))} type="button">移除</button></div></li>)}</ul> : <p className="py-10 text-center text-sm text-[#536168]">尚未選擇商品。關閉後可繼續瀏覽型錄。</p>}<label className="mt-4 block border-t border-[#D9E1E5] pt-5 text-sm font-bold">補充需求<textarea className="mt-2 min-h-24 w-full rounded-lg border border-[#B9CCD5] p-3 text-sm font-normal" placeholder="交期、配送地點、用途等" /></label><button className="mt-4 min-h-12 w-full rounded-lg bg-[#005DAA] text-sm font-bold text-white disabled:bg-[#A2B5BF]" disabled={!items.length} type="button">確認詢價內容</button><button className="mt-3 min-h-11 w-full rounded-lg border border-[#B9CCD5] text-sm font-bold text-[#536168]" onClick={() => setDrawerOpen(false)} type="button">繼續瀏覽商品</button><p className="mt-4 text-xs leading-5 text-[#536168]">送出後由所屬業務確認價格、供應與交期；本型錄不顯示即時價格或庫存。</p></aside></div>}
  </main>;
}
