"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

const banners = [
  { image: "/brand/banners/yuanjia-official-01.jpg", eyebrow: "", title: "", text: "" },
  { image: "/brand/banners/yuanjia-official-02.jpg", eyebrow: "", title: "", text: "" },
  { image: "/brand/banners/yuanjia-official-03.jpg", eyebrow: "", title: "", text: "" },
  { image: "/brand/banners/yuanjia-official-04.jpg", eyebrow: "", title: "", text: "" },
  { image: "/brand/banners/yuanjia-official-05.jpg", eyebrow: "", title: "", text: "" },
] as const;

const productGroups = [
  { key: "fish", label: "魚類", en: "FISH", image: "/products/b2b/B2B-FISH-001/main.jpg", copy: "整魚、切片與餐飲規格，適合多元菜單與通路需求。", items: "鮭魚｜鱈魚｜鯖魚" },
  { key: "shellfish", label: "蝦蟹貝類", en: "SHELLFISH", image: "/products/b2b/B2B-SHELL-001/main.jpg", copy: "從日常餐飲到節慶菜單，提供穩定規格與包裝選擇。", items: "蝦類｜蟹類｜貝類" },
  { key: "prepared", label: "調理食品", en: "VALUE ADDED", image: "/products/b2b/B2B-PREP-001/main.jpg", copy: "兼顧效率與風味的調理品，支援餐飲與加工應用。", items: "即食料理｜裹粉品｜加工品" },
  { key: "meat", label: "肉類", en: "MEAT", image: "/products/b2b/B2B-MEAT-001/main.jpg", copy: "依企業規格與使用情境，提供穩定的肉品供應。", items: "豬肉｜雞肉｜牛肉" },
] as const;

function SiteHeader() {
  return <header className="absolute inset-x-0 top-0 z-20 border-b border-white/20 bg-[#102C34]/35 text-white backdrop-blur-sm"><div className="mx-auto flex max-w-[1360px] items-center justify-between gap-6 px-6 py-5 lg:px-10"><div className="flex items-center gap-3"><Image alt="元家" height={42} src="/yens-logo.png" width={140} /><span className="h-7 w-px bg-white/40" /><span className="text-xs tracking-[0.22em] text-white/80">BUSINESS</span></div><nav className="hidden items-center gap-8 text-sm lg:flex"><a href="#products">元家產品</a><a href="#media">媒體報導</a><a href="#safety">食品安全</a><a href="#sustainability">永續責任</a></nav><a className="border border-white/70 px-4 py-2 text-sm font-semibold transition hover:bg-white hover:text-[#102C34]" href="/login">企業登入</a></div></header>;
}

export function Hero({ includeHeader = true }: { includeHeader?: boolean } = {}) {
  const [index, setIndex] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setIndex((current) => (current + 1) % banners.length), 7000); return () => window.clearInterval(timer); }, []);
  const banner = banners[index];
  return <section className="relative min-h-[680px] overflow-hidden bg-[#102C34] text-white"><Image alt="元家品牌與供應服務" className="object-cover transition-opacity duration-700" fill priority sizes="100vw" src={banner.image} /><div className="absolute inset-0 bg-gradient-to-r from-[#102C34]/35 via-transparent to-[#102C34]/20" />{includeHeader ? <SiteHeader /> : null}<div className="absolute inset-x-0 bottom-10 z-10 flex justify-center"><div className="rounded-full bg-[#102C34]/45 px-4 py-3" role="group" aria-label="Banner 切換"><div className="flex items-center gap-3">{banners.map((item, itemIndex) => <button aria-label={`切換至第 ${itemIndex + 1} 張 Banner`} aria-pressed={index === itemIndex} className={`h-1 transition-all ${index === itemIndex ? "w-14 bg-white" : "w-7 bg-white/50 hover:bg-white"}`} key={item.image} onClick={() => setIndex(itemIndex)} type="button" />)}</div></div></div></section>;
}

function Products() {
  return (
    <section className="bg-white py-24" id="products">
      <div className="mx-auto max-w-[1360px] px-6 lg:px-10">
        <div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-semibold tracking-[0.24em] text-[#00712F]">YUANJIA PRODUCTS</p><h2 className="mt-4 font-serif text-4xl text-[#17242A] sm:text-5xl">元家產品</h2></div><p className="max-w-md text-sm leading-7 text-[#536168]">依產品分類快速瀏覽，進入企業型錄查看完整規格與供應資訊。</p></div>
        <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{productGroups.map((group) => <a className="group relative block aspect-[.82/1] min-h-72 overflow-hidden bg-[#17353E]" href="/business/catalog" key={group.key}><Image alt={`${group.label}產品`} className="object-cover opacity-90 transition duration-500 group-hover:scale-105 group-hover:opacity-75" fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" src={group.image} /><div className="absolute inset-0 bg-gradient-to-t from-[#102C34]/85 via-[#102C34]/10 to-transparent" /><div className="absolute inset-x-5 bottom-5 text-white"><p className="text-[10px] font-semibold tracking-[0.22em] text-[#C8E5EC]">{group.en}</p><h3 className="mt-2 text-2xl font-semibold">{group.label}</h3><p className="mt-2 text-sm text-white/80">查看企業供應分類 <span className="ml-1 inline-block transition-transform group-hover:translate-x-1">→</span></p></div></a>)}</div>
        <div className="mt-10 text-center"><a className="inline-flex min-h-12 items-center border border-[#005DAA] px-7 text-sm font-semibold text-[#005DAA] transition hover:bg-[#005DAA] hover:text-white" href="/business/catalog">瀏覽完整企業型錄 →</a></div>
      </div>
    </section>
  );
}

function Media() { return <section className="border-t border-[#D9E1E5] bg-white py-24" id="media"><div className="mx-auto max-w-[1360px] px-6 lg:px-10"><div className="flex items-start gap-4"><span className="mt-1 h-14 w-1 bg-[#C84B31]" /><div><p className="text-xs font-semibold tracking-[0.24em] text-[#C84B31]">MEDIA & STORIES</p><h2 className="mt-3 font-serif text-4xl text-[#17242A]">NEWS</h2></div></div><div className="mt-12 grid gap-8 md:grid-cols-3"><article className="group"><div className="relative aspect-[1.55/1] overflow-hidden bg-[#EAF5FB]"><Image alt="上海國際漁業博覽會" className="object-cover transition duration-500 group-hover:scale-105" fill sizes="(min-width: 768px) 30vw, 100vw" src="/brand/channel-global.jpg" /></div><p className="mt-5 text-xs text-[#7C8585]">2026.08.24 · 活動訊息</p><h3 className="mt-3 text-xl font-semibold leading-8 text-[#17242A]">上海國際漁業博覽會 2026</h3><a className="mt-4 inline-block text-sm font-semibold text-[#005DAA]" href="/business/news/activities">閱讀全文 →</a></article><article className="group"><div className="relative aspect-[1.55/1] overflow-hidden bg-[#EAF5FB]"><Image alt="日本干貝尺寸規格表" className="object-cover transition duration-500 group-hover:scale-105" fill sizes="(min-width: 768px) 30vw, 100vw" src="/brand/company-origin.jpg" /></div><p className="mt-5 text-xs text-[#7C8585]">2026.07.02 · 元家資訊</p><h3 className="mt-3 text-xl font-semibold leading-8 text-[#17242A]">元家-日本干貝尺寸規格表</h3><a className="mt-4 inline-block text-sm font-semibold text-[#005DAA]" href="/business/news/yuanjia">閱讀全文 →</a></article><article className="group"><div className="relative aspect-[1.55/1] overflow-hidden bg-[#EAF5FB]"><Image alt="WOFEX MANILA 2026" className="object-cover transition duration-500 group-hover:scale-105" fill sizes="(min-width: 768px) 30vw, 100vw" src="/brand/channel-market.jpg" /></div><p className="mt-5 text-xs text-[#7C8585]">2026.07.30 · 活動訊息</p><h3 className="mt-3 text-xl font-semibold leading-8 text-[#17242A]">菲律賓國際食品展 WOFEX MANILA 2026</h3><a className="mt-4 inline-block text-sm font-semibold text-[#005DAA]" href="/business/news/activities">閱讀全文 →</a></article></div></div></section>; }

function Safety() { return <section className="relative overflow-hidden bg-[#53636A] py-24 text-white" id="safety"><Image alt="元家食品安全管理" className="object-cover opacity-25" fill sizes="100vw" src="/brand/quality-team.jpg" /><div className="absolute inset-0 bg-[#53636A]/55" /><div className="relative mx-auto max-w-[1360px] px-6 text-center lg:px-10"><p className="text-xs font-semibold tracking-[0.26em] text-[#D5EDF2]">FOOD SAFETY & QUALITY</p><h2 className="mt-5 font-serif text-4xl sm:text-5xl">食品安全</h2><div className="mx-auto mt-10 grid max-w-4xl grid-cols-2 items-center gap-8 border-y border-white/30 py-8 sm:grid-cols-4 sm:gap-10"><div className="relative h-24"><Image alt="HACCP 認證標誌" className="object-contain brightness-0 invert" fill sizes="160px" src="/brand/certifications/certig_01.png" /></div><div className="relative h-24"><Image alt="ISO 22000 認證標誌" className="object-contain brightness-0 invert" fill sizes="160px" src="/brand/certifications/certig_02.png" /></div><div className="relative h-24"><Image alt="HALAL 認證標誌" className="object-contain brightness-0 invert" fill sizes="160px" src="/brand/certifications/certig_03.png" /></div><div className="relative h-24"><Image alt="EFC 認證標誌" className="object-contain brightness-0 invert" fill sizes="160px" src="/brand/certifications/certig_04.png" /></div></div><div className="mx-auto mt-9 max-w-4xl space-y-2 text-base font-semibold leading-8 text-white/90 sm:text-lg"><p>元家對於食品安全的重視極富責任與使命感。</p><p>自主性的控管，以及政府政策的落實皆領先同業；近年食安風暴不斷，我們總能自信以對。</p></div><Link className="mt-8 inline-flex min-h-12 items-center border border-white/70 px-8 text-sm font-semibold transition hover:bg-white hover:text-[#53636A]" href="/business/about/quality-safety">了解更多</Link></div></section>; }

function Sustainability() { return <section className="bg-[#EAF5FB] py-24" id="sustainability"><div className="mx-auto grid max-w-[1360px] gap-10 px-6 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-10"><div><p className="text-xs font-semibold tracking-[0.24em] text-[#00712F]">SUSTAINABILITY</p><h2 className="mt-4 font-serif text-4xl leading-tight text-[#17242A] sm:text-5xl">永續發展</h2><p className="mt-6 max-w-md text-sm leading-7 text-[#536168]">從永續報告、公益行動到日常供應選擇，元家持續把企業責任放進每一個長期決策。</p><div className="mt-8"><Link className="inline-flex min-h-12 items-center bg-[#005DAA] px-7 text-sm font-semibold text-white transition hover:bg-[#004B89]" href="/business/about/sustainability">了解更多</Link></div></div><div className="grid gap-5 sm:grid-cols-2"><div className="relative aspect-[4/3] overflow-hidden"><Image alt="元家永續報告書" className="object-cover" fill sizes="(min-width: 640px) 30vw, 100vw" src="/brand/esg-2024-01.jpg" /></div><div className="relative mt-8 aspect-[4/3] overflow-hidden"><Image alt="元家永續供應" className="object-cover" fill sizes="(min-width: 640px) 30vw, 100vw" src="/brand/channel-service.jpg" /></div></div></div></section>; }

function Footer() { return <footer className="bg-[#252A2B] text-[#D6DEE0]"><div className="mx-auto grid max-w-[1360px] gap-8 px-6 py-12 sm:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1fr] lg:px-10"><div><Image alt="元家" height={42} src="/yens-logo.png" width={140} /><p className="mt-5 text-sm leading-7">元家企業股份有限公司<br />YEN &amp; Brothers Enterprise CO., LTD.</p></div><div><p className="text-xs tracking-[0.18em] text-[#9FD2E4]">元家產品</p><p className="mt-4 text-sm leading-7">魚類<br />蝦蟹貝類<br />調理食品<br />肉類</p></div><div><p className="text-xs tracking-[0.18em] text-[#9FD2E4]">企業服務</p><p className="mt-4 text-sm leading-7">企業型錄<br />需求篩選<br />大宗專案<br />詢價紀錄</p></div><div><p className="text-xs tracking-[0.18em] text-[#9FD2E4]">合作與責任</p><p className="mt-4 text-sm leading-7">食品安全<br />永續責任<br />媒體報導<br />聯絡元家</p></div></div><div className="border-t border-[#3A464A] px-6 py-5 text-center text-xs text-[#9EAAAD]">© 2026 YEN &amp; Brothers Enterprise CO., LTD. · B2B 首頁概念預覽</div></footer>; }

export { Products, Media, Safety, Sustainability, Footer };

export default function HomepagePreviewClient() { return <div className="min-h-screen bg-[#F7F6F2] font-sans text-[#17242A]"><div className="border-b border-[#E2B04A] bg-[#FFF7E1] px-4 py-2 text-center text-xs text-[#6F5112]">B2B 首頁概念預覽 · 尚未套用正式官網</div><Hero /><Products /><Media /><Safety /><Sustainability /><Footer /></div>; }
