"use client";

import { useEffect } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";

import type { B2BCatalogData, B2BProduct } from "@/lib/b2b/catalog";

type JourneyView = "catalog" | "detail" | "workspace";

const views: Array<{ key: JourneyView; label: string }> = [
  { key: "catalog", label: "1 · 企業型錄" },
  { key: "detail", label: "2 · 商品詳情" },
  { key: "workspace", label: "3 · 詢價工作台" },
];

function ProductArtwork({ className = "" }: { className?: string }) {
  return <div className={`relative overflow-hidden bg-[#D7EAF4] ${className}`}><div className="absolute -right-10 -top-12 size-52 rounded-full border-[28px] border-white/55" /><div className="absolute bottom-8 left-8 h-16 w-36 rounded-[50%] bg-[#005DAA]" /><div className="absolute bottom-[4.1rem] left-28 size-4 rounded-full bg-white" /><div className="absolute bottom-10 left-5 border-y-[18px] border-r-[30px] border-y-transparent border-r-[#00457F]" /></div>;
}

function CatalogView({ products }: { products: B2BProduct[] }) {
  return <div className="space-y-10"><section className="grid overflow-hidden rounded-3xl bg-[#00457F] text-white lg:grid-cols-[1.05fr_.95fr]"><div className="p-8 sm:p-12"><p className="text-xs font-bold tracking-[.18em] text-[#A8D6F0]">YUANJIA BUSINESS CATALOG</p><h1 className="mt-4 max-w-xl text-3xl font-bold leading-tight sm:text-5xl">從食材規格開始，<br />找到適合您的商品。</h1><p className="mt-5 max-w-lg leading-7 text-[#D7EAF4]">提供企業客戶瀏覽品類、規格、包裝與產地資訊；有興趣的品項再加入詢價單，由業務確認報價。</p><div className="mt-8 rounded-xl bg-white p-1.5 text-[#536168]"><div className="flex min-h-12 items-center px-4 text-sm">搜尋品名、商品代碼或規格</div></div></div><ProductArtwork className="min-h-64" /></section><section><div className="flex items-end justify-between gap-5"><div><p className="text-xs font-bold tracking-[.16em] text-[#005DAA]">EXPLORE BY CATEGORY</p><h2 className="mt-2 text-2xl font-bold">依品類探索</h2></div><p className="text-sm text-[#536168]">先看型錄，不必立即詢價</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["魚類", "蝦蟹類", "調理食品", "品牌商品"].map((category, index) => <article className="group rounded-2xl border border-[#D9E1E5] bg-white p-5" key={category}><div className={`grid size-11 place-items-center rounded-xl text-sm font-bold ${index === 2 ? "bg-[#EAF6EE] text-[#00712F]" : "bg-[#EAF5FB] text-[#005DAA]"}`}>{category.slice(0, 2)}</div><h3 className="mt-6 font-bold">{category}</h3><p className="mt-2 text-sm text-[#536168]">瀏覽商品與採購規格</p></article>)}</div></section><section><p className="text-xs font-bold tracking-[.16em] text-[#005DAA]">FEATURED PRODUCTS</p><h2 className="mt-2 text-2xl font-bold">推薦商品</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.slice(0, 3).map((product) => <article className="overflow-hidden rounded-2xl border border-[#D9E1E5] bg-white" key={product.id}><ProductArtwork className="aspect-[16/9]" /><div className="p-5"><p className="text-xs font-bold text-[#005DAA]">{product.productCode}</p><h3 className="mt-2 text-lg font-bold">{product.name}</h3><p className="mt-2 text-sm text-[#536168]">{product.specification} · {product.origin}</p><p className="mt-5 text-sm font-bold text-[#005DAA]">查看商品詳情 →</p></div></article>)}</div></section></div>;
}

function DetailView({ product }: { product: B2BProduct | undefined }) {
  if (!product) return null;
  return <div><p className="text-sm text-[#536168]">企業型錄 / {product.category} / {product.name}</p><section className="mt-5 grid gap-8 rounded-3xl border border-[#D9E1E5] bg-white p-5 lg:grid-cols-2 lg:p-8"><ProductArtwork className="min-h-80 rounded-2xl" /><div className="flex flex-col"><p className="text-xs font-bold tracking-[.16em] text-[#005DAA]">{product.productCode}</p><h1 className="mt-3 text-3xl font-bold">{product.name}</h1><p className="mt-3 text-[#536168]">{product.brand} · {product.category}</p><dl className="mt-8 divide-y divide-[#E2E8EB] border-y border-[#E2E8EB] text-sm"><div className="grid grid-cols-[6rem_1fr] py-4"><dt className="font-semibold text-[#536168]">規格</dt><dd>{product.specification}</dd></div><div className="grid grid-cols-[6rem_1fr] py-4"><dt className="font-semibold text-[#536168]">包裝</dt><dd>{product.packaging ?? "詳見商品規格"}</dd></div><div className="grid grid-cols-[6rem_1fr] py-4"><dt className="font-semibold text-[#536168]">產地</dt><dd>{product.origin}</dd></div><div className="grid grid-cols-[6rem_1fr] py-4"><dt className="font-semibold text-[#536168]">保存</dt><dd>{product.storageMethod}</dd></div></dl><div className="mt-auto pt-7"><button className="min-h-12 w-full rounded-lg bg-[#005DAA] px-4 font-bold text-white">選擇規格，加入詢價單</button><p className="mt-3 text-xs leading-5 text-[#536168]">價格、實際供應與交期由業務確認。</p></div></div></section><section className="mt-8 grid gap-8 lg:grid-cols-[1fr_18rem]"><div><h2 className="text-xl font-bold">產品特色</h2><p className="mt-3 max-w-2xl leading-8 text-[#536168]">{product.description || "此處呈現商品特色、料理方式、認證與適用通路等資訊，讓客戶先充分理解產品，再決定是否詢價。"}</p></div><aside className="rounded-2xl bg-[#EAF6EE] p-5"><p className="text-xs font-bold tracking-[.14em] text-[#00712F]">PRODUCT ASSURANCE</p><h3 className="mt-2 font-bold">來源與安心資訊</h3><p className="mt-2 text-sm leading-6 text-[#3B6450]">認證、加工與產地資訊放在商品頁，方便客戶閱讀。</p></aside></section></div>;
}

function WorkspaceView({ products }: { products: B2BProduct[] }) {
  return <div className="grid gap-6 xl:grid-cols-[1fr_20rem]"><section><p className="text-xs font-bold tracking-[.16em] text-[#005DAA]">INQUIRY WORKSPACE</p><h1 className="mt-2 text-3xl font-bold">整理本次詢價需求</h1><p className="mt-3 leading-7 text-[#536168]">這是客戶確認想詢問的商品後才進入的頁面，不是型錄首頁。</p><div className="mt-7 overflow-hidden rounded-2xl border border-[#D9E1E5] bg-white"><div className="grid grid-cols-[1fr_8rem_7rem] gap-3 border-b border-[#D9E1E5] bg-[#F7F6F2] px-5 py-3 text-xs font-bold text-[#536168]"><span>已選商品</span><span>規格</span><span>需求量</span></div>{products.slice(0, 2).map((product, index) => <div className="grid grid-cols-[1fr_8rem_7rem] gap-3 border-b border-[#E2E8EB] px-5 py-5 text-sm last:border-b-0" key={product.id}><div><p className="font-bold">{product.name}</p><p className="mt-1 text-xs text-[#536168]">{product.productCode}</p></div><p>{product.specification}</p><p>{index + 1} 箱</p></div>)}</div><div className="mt-6 rounded-2xl border border-[#D6E8F2] bg-[#F4FAFD] p-5"><h2 className="font-bold">補充需求</h2><p className="mt-2 text-sm text-[#536168]">希望交期、配送地區、使用通路與其他備註。</p><div className="mt-4 min-h-24 rounded-lg border border-[#B9CCD5] bg-white p-3 text-sm text-[#809099]">填寫補充需求…</div></div></section><aside className="h-fit rounded-2xl bg-[#00457F] p-6 text-white xl:sticky xl:top-6"><p className="text-xs font-bold tracking-[.16em] text-[#A8D6F0]">NEXT STEP</p><h2 className="mt-3 text-xl font-bold">送出詢價需求</h2><p className="mt-3 text-sm leading-6 text-[#D7EAF4]">業務收到後確認規格、供應與報價，再與客戶聯繫。</p><button className="mt-7 min-h-12 w-full rounded-lg bg-white px-4 text-sm font-bold text-[#00457F]">確認詢價內容</button><p className="mt-4 text-xs leading-5 text-[#A8D6F0]">不是下單，也不代表庫存或價格已確認。</p></aside></div>;
}

export default function CatalogJourneyPrototype({ catalog, companyName }: { catalog: B2BCatalogData; companyName: string }) {
  const pathname = usePathname();
  const router = useRouter();
  const params = useSearchParams();
  const current = (params.get("journey") as JourneyView | null) ?? "catalog";
  const index = views.findIndex((view) => view.key === current);
  const activeView = index === -1 ? "catalog" : current;
  const go = (next: JourneyView) => { const search = new URLSearchParams(params.toString()); search.set("prototype", "journey"); search.set("journey", next); router.replace(`${pathname}?${search.toString()}`); };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === "ArrowLeft" || event.key === "ArrowRight") { const move = event.key === "ArrowLeft" ? -1 : 1; go(views[(Math.max(index, 0) + move + views.length) % views.length].key); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); });
  return <main className="min-h-screen bg-[#F7F6F2] px-5 py-8 pb-28 text-[#17242A]" style={{ fontFamily: '"Noto Sans TC", "Microsoft JhengHei", system-ui, sans-serif' }}><div className="mx-auto max-w-[1200px]"><header className="mb-8 flex flex-wrap items-start justify-between gap-4 border-b border-[#D9E1E5] pb-5"><div><p className="text-xs font-bold tracking-[.16em] text-[#005DAA]">THROWAWAY PROTOTYPE · B2B JOURNEY</p><h1 className="mt-2 text-lg font-bold">{companyName} 的企業採購流程預覽</h1></div><p className="max-w-xs text-sm leading-6 text-[#536168]">狀態：{views.find((view) => view.key === activeView)?.label}；此草圖沒有儲存或送單功能。</p></header>{activeView === "catalog" ? <CatalogView products={catalog.products} /> : null}{activeView === "detail" ? <DetailView product={catalog.products[0]} /> : null}{activeView === "workspace" ? <WorkspaceView products={catalog.products} /> : null}</div>{process.env.NODE_ENV !== "production" ? <nav aria-label="切換預覽畫面" className="fixed inset-x-0 bottom-5 z-50 mx-auto flex w-fit items-center gap-2 rounded-full bg-[#17242A] p-2 text-sm text-white shadow-2xl"><button aria-label="上一頁" className="grid size-9 place-items-center rounded-full bg-white/15" onClick={() => go(views[(Math.max(index, 0) + views.length - 1) % views.length].key)} type="button">←</button>{views.map((view) => <button className={`rounded-full px-3 py-2 font-bold ${view.key === activeView ? "bg-white text-[#17242A]" : "text-white/75"}`} key={view.key} onClick={() => go(view.key)} type="button">{view.label}</button>)}<button aria-label="下一頁" className="grid size-9 place-items-center rounded-full bg-white/15" onClick={() => go(views[(Math.max(index, 0) + 1) % views.length].key)} type="button">→</button></nav> : null}</main>;
}
