"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type SpecificationRow = { id: string; packaging: string; specification: string };
type InquiryLine = SpecificationRow & { quantity: number };

const product = { brand: "元家", category: "魚類", code: "DEMO-FISH-001", name: "鮭魚菲力切塊", origin: "智利", storage: "冷凍 -18°C 以下" };
const specificationRows: SpecificationRow[] = [
  { id: "100-150", specification: "100–150g／片", packaging: "20片／箱" },
  { id: "150-200", specification: "150–200g／片", packaging: "15片／箱" },
  { id: "200-250", specification: "200–250g／片", packaging: "10片／箱" },
];

function QuantityInput({ disabled, onChange, value }: { disabled?: boolean; onChange: (value: number) => void; value: number }) {
  return <div className="flex min-h-10 items-center justify-between rounded-lg border border-[#c9d7dc] bg-white"><button aria-label="減少箱數" className="grid size-10 place-items-center text-lg text-[#52656d] disabled:text-[#b8c6cb]" disabled={disabled || value <= 1} onClick={() => onChange(Math.max(1, value - 1))} type="button">−</button><output className="min-w-7 text-center text-sm font-bold">{value}</output><button aria-label="增加箱數" className="grid size-10 place-items-center text-lg text-[#0062aa] disabled:text-[#b8c6cb]" disabled={disabled} onClick={() => onChange(value + 1)} type="button">＋</button></div>;
}

export default function SpecificationPreviewPage() {
  const [selected, setSelected] = useState<Record<string, number>>({});
  const [otherSelected, setOtherSelected] = useState(false);
  const [otherText, setOtherText] = useState("");
  const [otherQuantity, setOtherQuantity] = useState(1);
  const [inquiryLines, setInquiryLines] = useState<InquiryLine[]>([]);

  const chosenRows = useMemo(() => specificationRows.filter((row) => selected[row.id]).map((row) => ({ ...row, quantity: selected[row.id] })), [selected]);
  const otherLine = otherSelected && otherText.trim() ? { id: "other", specification: `其他需求：${otherText.trim()}`, packaging: "由業務確認", quantity: otherQuantity } : null;
  const canAdd = Boolean(chosenRows.length || otherLine);
  const toggleRow = (id: string) => setSelected((current) => current[id] ? Object.fromEntries(Object.entries(current).filter(([key]) => key !== id)) : { ...current, [id]: 1 });
  const updateQuantity = (id: string, quantity: number) => setSelected((current) => ({ ...current, [id]: quantity }));
  const addToInquiry = () => setInquiryLines([...chosenRows, ...(otherLine ? [otherLine] : [])]);

  return <main className="min-h-screen bg-[#f7f6f2] text-[#18262d]" style={{ fontFamily: '"Noto Sans TC", "Microsoft JhengHei", system-ui, sans-serif' }}>
    <header className="sticky top-0 z-40 border-b border-[#d8e0e2] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1240px] items-center justify-between gap-3 px-5 py-3 lg:px-8"><div><p className="text-xs font-bold tracking-[.16em] text-[#0062aa]">YUANJIA BUSINESS · UI PREVIEW</p><h1 className="mt-1 text-base font-bold sm:text-xl">多規格詢價選擇</h1></div><div className="flex items-center gap-2"><Link className="hidden rounded-lg px-3 py-2 text-sm font-semibold text-[#52656d] hover:bg-[#edf5f8] sm:block" href="/catalog-preview/fdd">返回 FDD 型錄</Link><span className="rounded-lg border border-[#91b9ce] bg-[#f5fbfe] px-3 py-2 text-sm font-bold text-[#0062aa]">詢價單（{inquiryLines.length}）</span></div></div></header>
    <div className="mx-auto max-w-[1240px] px-5 py-7 lg:px-8 lg:py-10"><div className="border-b border-[#d9e1e4] pb-5"><p className="text-xs font-bold tracking-[.15em] text-[#0062aa]">DEMO ONLY · NOT CONNECTED TO SUPABASE</p><h2 className="mt-2 text-3xl font-bold tracking-tight">選擇希望規格與數量</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#52656d]">型錄卡可顯示「多種規格可選」；商品細項可列出所有規格。此頁讓企業客戶同時選擇多個規格、各自填寫箱數，或補充其他規格／包裝需求。</p></div>
      <div className="mt-7 grid gap-6 lg:grid-cols-[18rem_minmax(0,1fr)_19rem]">
        <aside className="h-fit rounded-2xl border border-[#d9e1e4] bg-white p-5 shadow-sm lg:sticky lg:top-24"><p className="text-xs font-bold tracking-[.14em] text-[#0062aa]">SELECTED PRODUCT</p><div className="mt-4 grid aspect-[16/9] place-items-center overflow-hidden rounded-xl bg-[linear-gradient(135deg,#e4f3f8,#f7fbfc)]"><span className="rounded-full border border-[#9ec4d7] bg-white px-3 py-2 text-sm font-bold text-[#0062aa]">鮭魚</span></div><p className="mt-5 text-xs font-bold tracking-[.08em] text-[#0062aa]">{product.code}</p><h3 className="mt-2 text-xl font-bold">{product.name}</h3><p className="mt-1 text-sm text-[#52656d]">{product.brand}・{product.category}</p><dl className="mt-5 divide-y divide-[#e2e8ea] border-y border-[#e2e8ea] text-sm"><div className="grid grid-cols-[4rem_1fr] gap-2 py-3"><dt className="font-semibold text-[#52656d]">規格</dt><dd>3 種可選</dd></div><div className="grid grid-cols-[4rem_1fr] gap-2 py-3"><dt className="font-semibold text-[#52656d]">產地</dt><dd>{product.origin}</dd></div><div className="grid grid-cols-[4rem_1fr] gap-2 py-3"><dt className="font-semibold text-[#52656d]">保存</dt><dd>{product.storage}</dd></div></dl><div className="mt-4 flex flex-wrap gap-1.5">{specificationRows.map((row) => <span className="rounded-full bg-[#eaf5fb] px-2 py-1 text-xs font-semibold text-[#386275]" key={row.id}>{row.specification}</span>)}</div></aside>
        <section className="rounded-2xl border border-[#d9e1e4] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.14em] text-[#0062aa]">PREFERRED SPECIFICATIONS</p><h3 className="mt-2 text-2xl font-bold">希望規格</h3><p className="mt-2 text-sm leading-6 text-[#52656d]">可同時選擇多種規格，並為每種規格分別填寫預估箱數。</p></div><span className="rounded-full bg-[#fff8e8] px-3 py-1.5 text-xs font-bold text-[#806300]">展示用資料</span></div>
          <fieldset className="mt-7"><legend className="sr-only">選擇希望規格與數量</legend><div className="overflow-hidden rounded-xl border border-[#d9e1e4]"><div className="hidden grid-cols-[2.5rem_minmax(0,1fr)_7rem_9rem] gap-3 bg-[#f3f7f8] px-4 py-3 text-xs font-bold text-[#52656d] sm:grid"><span>選擇</span><span>規格</span><span>包裝</span><span>預估箱數</span></div>{specificationRows.map((row) => { const checked = Boolean(selected[row.id]); return <div className={`grid gap-3 border-t border-[#e2e8ea] p-4 sm:grid-cols-[2.5rem_minmax(0,1fr)_7rem_9rem] sm:items-center ${checked ? "bg-[#f4fafd]" : "bg-white"}`} key={row.id}><label className="flex cursor-pointer items-center gap-3 sm:contents"><input checked={checked} className="size-4 accent-[#0062aa]" onChange={() => { toggleRow(row.id); setInquiryLines([]); }} type="checkbox" /><span className="font-bold">{row.specification}</span></label><span className="text-sm text-[#52656d]">{row.packaging}</span><QuantityInput disabled={!checked} onChange={(value) => { updateQuantity(row.id, value); setInquiryLines([]); }} value={selected[row.id] ?? 1} /></div>; })}</div></fieldset>
          <section className={`mt-4 rounded-xl border p-4 ${otherSelected ? "border-[#8fb9ce] bg-[#f4fafd]" : "border-[#d9e1e4]"}`}><label className="flex cursor-pointer items-center gap-3 text-sm font-bold"><input checked={otherSelected} className="size-4 accent-[#0062aa]" onChange={(event) => { setOtherSelected(event.target.checked); setInquiryLines([]); }} type="checkbox" />其他規格／包裝需求</label>{otherSelected ? <div className="mt-4 grid gap-4 sm:grid-cols-[minmax(0,1fr)_9rem]"><label className="text-sm font-semibold">請描述需求<textarea autoFocus className="mt-2 min-h-24 w-full resize-y rounded-lg border border-[#b9ccd5] p-3 text-sm font-normal outline-none placeholder:text-[#809099] focus:border-[#0062aa] focus:ring-4 focus:ring-[#eaf5fb]" onChange={(event) => { setOtherText(event.target.value); setInquiryLines([]); }} placeholder="例如：300g／片、去皮去刺、每箱 10kg" value={otherText} /></label><label className="text-sm font-semibold">預估箱數<span className="mt-2 block"><QuantityInput onChange={(value) => { setOtherQuantity(value); setInquiryLines([]); }} value={otherQuantity} /></span></label></div> : null}</section>
          <div className="mt-7 border-t border-[#e2e8ea] pt-6"><button className="min-h-12 w-full rounded-lg bg-[#0062aa] px-5 text-sm font-bold text-white transition hover:bg-[#004f8c] disabled:cursor-not-allowed disabled:bg-[#a2b5bf]" disabled={!canAdd} onClick={addToInquiry} type="button">加入詢價單</button><p className="mt-3 text-xs leading-5 text-[#52656d]">實際可供規格、包裝、交期與報價均由業務確認；這不是即時下單，也不保證可客製。</p></div>
        </section>
        <aside aria-live="polite" className="h-fit rounded-2xl border border-[#b9d5e5] bg-white p-5 shadow-[0_10px_24px_rgba(0,93,170,.06)] lg:sticky lg:top-24"><p className="text-xs font-bold tracking-[.14em] text-[#0062aa]">INQUIRY SUMMARY</p><h3 className="mt-2 text-xl font-bold">詢價單</h3>{inquiryLines.length ? <div className="mt-5 divide-y divide-[#e2e8ea] border-y border-[#e2e8ea]">{inquiryLines.map((line) => <div className="py-4 text-sm" key={line.id}><p className="font-bold">{product.name}</p><p className="mt-2 font-semibold text-[#00538f]">{line.specification}</p><p className="mt-1 text-xs text-[#52656d]">{line.packaging}・預估 {line.quantity} 箱</p></div>)}</div> : <div className="mt-5 border-t border-[#e2e8ea] pt-5 text-sm leading-6 text-[#52656d]"><div className="grid size-11 place-items-center rounded-full bg-[#eaf5fb] text-xl text-[#0062aa]">＋</div><p className="mt-3 font-semibold text-[#18262d]">尚未選擇規格</p><p className="mt-1">可選多種規格，加入後會分列顯示。</p></div>}<button className="mt-5 min-h-11 w-full rounded-lg border border-[#b7cbd5] text-sm font-bold text-[#52656d] disabled:cursor-not-allowed disabled:border-[#e2e8ea] disabled:text-[#a2b5bf]" disabled={!inquiryLines.length} onClick={() => setInquiryLines([])} type="button">清除展示詢價單</button><p className="mt-4 border-t border-[#e2e8ea] pt-4 text-xs leading-5 text-[#52656d]">純前端預覽：不會建立詢價單或寫入任何資料。</p></aside>
      </div></div>
  </main>;
}
